# Generated by Django 4.1.5 on 2023-01-29 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List_dolzhnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dolzhnost', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='list_mecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_mecto', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='list_promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_promotion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('patronymic', models.CharField(max_length=40)),
                ('self_phone_number', models.IntegerField(blank=True)),
                ('home_phone_number', models.IntegerField(blank=True)),
                ('passport_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zvanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_get', models.DateField(null=True)),
                ('name_doc', models.CharField(max_length=40)),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_start_work', models.DateField(null=True)),
                ('data_end_work', models.DateField(null=True)),
                ('dolzhnost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.list_dolzhnost')),
                ('mesto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.list_mecto')),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
                ('promotion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.list_promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zukluchenie', models.DateField(null=True)),
                ('data_okonchanie', models.DateField(null=True)),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
    ]
