# Generated by Django 4.1.5 on 2023-01-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('patronymic', models.CharField(max_length=40)),
                ('self_phone_number', models.IntegerField()),
                ('home_phone_number', models.IntegerField()),
                ('passport_number', models.IntegerField()),
            ],
        ),
    ]
