# Generated by Django 4.1.5 on 2023-01-24 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
                ('surname', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=40, verbose_name='Отчество')),
                ('self_phone_number', models.IntegerField(blank=True, verbose_name='Личный номер телефона')),
                ('home_phone_number', models.IntegerField(blank=True, verbose_name='Домашний телефон')),
                ('passport_number', models.IntegerField(verbose_name='Номер паспорта')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.CharField(max_length=40, verbose_name='Поощрение')),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Поощрение',
                'verbose_name_plural': 'Поощрения',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zukluchenie', models.DateField(null=True, verbose_name='Дата заключения')),
                ('data_okonchanie', models.DateField(null=True, verbose_name='Дата окончания')),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
            },
        ),
    ]
