# Generated by Django 4.1.5 on 2023-01-24 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vid_Rodstvenniki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид родственников',
                'verbose_name_plural': 'Виды родтсвенников',
            },
        ),
        migrations.CreateModel(
            name='vid_Vziskanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид взыскания',
                'verbose_name_plural': 'Виды взысканий',
            },
        ),
        migrations.CreateModel(
            name='vid_Zavedenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Название УЗ',
                'verbose_name_plural': 'Названия УЗ',
            },
        ),
        migrations.CreateModel(
            name='Vziskanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='Сотрудник')),
                ('vid_vziskania', models.ForeignKey(max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.vid_vziskanie', verbose_name='Вид взыскания')),
            ],
            options={
                'verbose_name': 'Взыскание',
                'verbose_name_plural': 'Взыскания',
            },
        ),
        migrations.CreateModel(
            name='Rodstvenniki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
                ('surname', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('patronomyc', models.CharField(max_length=40, verbose_name='Отчество')),
                ('date_born', models.DateField(null=True, verbose_name='Дата рождения')),
                ('date_brak', models.DateField(null=True, verbose_name='Дата брака')),
                ('date_razvod', models.DateField(null=True, verbose_name='Дата развода')),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='Сотрудник')),
                ('vid_svyazi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.vid_rodstvenniki', verbose_name='Вид родственной связи')),
            ],
            options={
                'verbose_name': 'Родственники',
                'verbose_name_plural': 'Родственники',
            },
        ),
        migrations.CreateModel(
            name='Obrazovanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_postuplenia', models.DateField(null=True, verbose_name='Дата поступления')),
                ('date_okonchanie', models.DateField(null=True, verbose_name='Дата окончания')),
                ('obrazovanie_perepodgotovka', models.CharField(max_length=40, verbose_name='Образование/Переподготовка')),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='Сотрудник')),
                ('vuz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.vid_zavedenie', verbose_name='Наименования УЗ')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образования',
            },
        ),
    ]
