# Generated by Django 4.1.5 on 2023-01-29 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vid_Rodstvenniki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rodstvennik', models.CharField(max_length=40, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид родственников',
                'verbose_name_plural': 'Виды родтсвенников',
            },
        ),
        migrations.CreateModel(
            name='Rodstvenniki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rod', models.CharField(max_length=40, verbose_name='Имя')),
                ('surname_rod', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('patronomyc', models.CharField(max_length=40, verbose_name='Отчество')),
                ('date_born', models.DateField(null=True, verbose_name='Дата рождения')),
                ('date_brak', models.DateField(null=True, verbose_name='Дата брака')),
                ('date_razvod', models.DateField(null=True, verbose_name='Дата развода')),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='Сотрудник')),
                ('vid_svyazi', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.vid_rodstvenniki', verbose_name='Вид родственной связи')),
            ],
            options={
                'verbose_name': 'Родственники',
                'verbose_name_plural': 'Родственники',
            },
        ),
    ]
