# Generated by Django 4.1.5 on 2023-01-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_forma_soutrudnik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='home_phone_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='self_phone_number',
            field=models.IntegerField(blank=True),
        ),
    ]
