# Generated by Django 4.1.5 on 2023-01-25 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_dolzhnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dolzhnost', models.CharField(max_length=40)),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.work')),
            ],
        ),
    ]
