# Generated by Django 4.1.5 on 2023-01-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_home_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zukluchenie', models.DateField()),
                ('data_okonchanie', models.DateField()),
            ],
        ),
    ]
