# Generated by Django 4.1.5 on 2023-01-29 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_vid_rodstvenniki_rodstvenniki'),
    ]

    operations = [
        migrations.CreateModel(
            name='vid_Zavedenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_vuz', models.CharField(max_length=40, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Название УЗ',
                'verbose_name_plural': 'Названия УЗ',
            },
        ),
        migrations.CreateModel(
            name='Obrazovanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_postuplen', models.DateField(null=True, verbose_name='Дата поступления')),
                ('date_okonch', models.DateField(null=True, verbose_name='Дата окончания')),
                ('obrazovanie_perepodgotovka', models.CharField(max_length=40, verbose_name='Образование/Переподготовка')),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='Сотрудник')),
                ('vuz', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.vid_zavedenie', verbose_name='Наименования УЗ')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образования',
            },
        ),
    ]
