# Generated by Django 4.1.5 on 2023-01-25 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_list_dolzhnost'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='mesto',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='Zvanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_get', models.DateField(null=True)),
                ('name_doc', models.CharField(max_length=40)),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='list_mecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_mecto', models.CharField(max_length=40)),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.work')),
            ],
        ),
    ]
