# Generated by Django 4.1.5 on 2023-01-24 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_obrazovanie_vuz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrazovanie',
            name='vuz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.vid_zavedenie', verbose_name='Наименования УЗ'),
        ),
    ]
