# Generated by Django 4.1.5 on 2023-01-22 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_promotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='promption',
            new_name='promotion',
        ),
    ]
