# Generated by Django 4.1.5 on 2023-01-21 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.contract'),
        ),
    ]
