# Generated by Django 4.1.5 on 2023-01-27 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_work_mesto_zvanie_list_mecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list_dolzhnost',
            name='personal',
        ),
        migrations.RemoveField(
            model_name='list_mecto',
            name='personal',
        ),
    ]
