# Generated by Django 4.1.5 on 2023-01-30 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_patronomyc_rodstvenniki_patronomyc_rod'),
    ]

    operations = [
        migrations.CreateModel(
            name='vid_Vziskanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_vziskanie', models.CharField(blank=True, max_length=40, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид взыскания',
                'verbose_name_plural': 'Виды взысканий',
            },
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Контракт', 'verbose_name_plural': 'Контракт'},
        ),
        migrations.AlterModelOptions(
            name='list_dolzhnost',
            options={'verbose_name': 'Список должностей', 'verbose_name_plural': 'Список должностей'},
        ),
        migrations.AlterModelOptions(
            name='list_mecto',
            options={'verbose_name': 'Список в/ч', 'verbose_name_plural': 'Список в/ч'},
        ),
        migrations.AlterModelOptions(
            name='list_promotion',
            options={'verbose_name': 'Список поощерений', 'verbose_name_plural': 'Список поощерений'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Поощерения', 'verbose_name_plural': 'Поощерения'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Линые данные', 'verbose_name_plural': 'Личные данные'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Работа', 'verbose_name_plural': 'Работа'},
        ),
        migrations.AlterModelOptions(
            name='zvanie',
            options={'verbose_name': 'Звания', 'verbose_name_plural': 'Звания'},
        ),
        migrations.CreateModel(
            name='Vziskanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='Сотрудник')),
                ('vid_vziskania', models.OneToOneField(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.vid_vziskanie', verbose_name='Вид взыскания')),
            ],
            options={
                'verbose_name': 'Взыскание',
                'verbose_name_plural': 'Взыскания',
            },
        ),
    ]
