# Generated by Django 4.1.5 on 2023-01-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_promption_promotion_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='personal_id',
            field=models.IntegerField(null=True),
        ),
    ]
