# Generated by Django 4.1.5 on 2023-01-25 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_obrazovanie_vuz_alter_rodstvenniki_vid_svyazi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vziskanie',
            name='vid_vziskania',
            field=models.OneToOneField(max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vid', to='user.vid_vziskanie', verbose_name='Вид взыскания'),
        ),
    ]
