# Generated by Django 4.1.5 on 2023-01-22 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_promotion_personal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='promotiom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.promotion'),
        ),
    ]
