# Generated by Django 4.1.5 on 2023-01-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_contract'),
        ('user', '0006_user_promotiom'),
    ]

    operations = [
    ]
