# Generated by Django 4.1.5 on 2023-01-23 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_promotiom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='promotiom',
        ),
        migrations.AddField(
            model_name='user',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.promotion'),
        ),
    ]
