# Generated by Django 4.1.5 on 2023-01-25 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_vziskanie_vid_vziskania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vziskanie',
            name='vid_vziskania',
            field=models.OneToOneField(max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.vid_vziskanie', verbose_name='Вид взыскания'),
        ),
    ]
