# Generated by Django 4.1.5 on 2023-01-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_vziskanie_vid_vziskania'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vid_rodstvenniki',
            old_name='name',
            new_name='name_rodstvennik',
        ),
        migrations.RenameField(
            model_name='vid_vziskanie',
            old_name='name',
            new_name='name_vziskanie',
        ),
        migrations.RenameField(
            model_name='vid_zavedenie',
            old_name='name',
            new_name='name_vuz',
        ),
    ]
