# Generated by Django 4.1.5 on 2023-01-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_merge_0005_alter_user_contract_0006_user_promotiom'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='personal_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='data_okonchanie',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='data_zukluchenie',
            field=models.DateField(null=True),
        ),
    ]
