# Generated by Django 4.1.5 on 2023-01-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_contract_personal_id_alter_contract_data_okonchanie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='promotiom',
            new_name='promotion',
        ),
    ]
