# Generated by Django 4.1.5 on 2023-01-25 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_name_vid_rodstvenniki_name_rodstvennik_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obrazovanie',
            old_name='date_okonchanie',
            new_name='date_okonch',
        ),
        migrations.RenameField(
            model_name='obrazovanie',
            old_name='date_postuplenia',
            new_name='date_postuplen',
        ),
        migrations.RenameField(
            model_name='rodstvenniki',
            old_name='name',
            new_name='name_rod',
        ),
        migrations.RenameField(
            model_name='rodstvenniki',
            old_name='surname',
            new_name='surname_rod',
        ),
    ]
