# Generated by Django 4.1.5 on 2023-01-23 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_promotiom_user_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contract',
        ),
        migrations.AlterField(
            model_name='contract',
            name='personal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
    ]
