# Generated by Django 4.1.5 on 2023-01-25 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_date_okonchanie_obrazovanie_date_okonch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrazovanie',
            name='vuz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.vid_zavedenie', verbose_name='Наименования УЗ'),
        ),
        migrations.AlterField(
            model_name='rodstvenniki',
            name='vid_svyazi',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.vid_rodstvenniki', verbose_name='Вид родственной связи'),
        ),
        migrations.AlterField(
            model_name='vziskanie',
            name='vid_vziskania',
            field=models.OneToOneField(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.vid_vziskanie', verbose_name='Вид взыскания'),
        ),
    ]
