# Generated by Django 4.1.5 on 2023-01-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_obrazovanie_vuz_alter_rodstvenniki_vid_svyazi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vid_vziskanie',
            name='name_vziskanie',
            field=models.CharField(choices=[('1', 'Нарушение ФО'), ('2', 'Опаздание')], max_length=40, verbose_name='Наименование'),
        ),
    ]
