# Generated by Django 4.1.5 on 2023-01-23 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_user_contract_alter_contract_personal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='personal_id',
            new_name='personal',
        ),
    ]
