# Generated by Django 4.1.5 on 2023-01-23 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_personal_id_contract_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='personal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='Сотрудник'),
        ),
    ]
