# Generated by Django 4.1.5 on 2023-01-24 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_contract_data_okonchanie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Контракт', 'verbose_name_plural': 'Контракты'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
